name: Publish Package

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    name: Publish Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Generate TS Protobuf
        run: yarn run generate

      - name: Publish package
        run: npm publish --access public
